<a href="https://colab.research.google.com/github/rehanmehdichandio/Numpy-Practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
#2D array
b=np.array([[1,2,3],[3,4,5]])

In [ ]:
print(b)

[[1 2 3]
 [3 4 5]]


In [ ]:
np.arange(2,13,2)

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
np.arange(2,13,2,dtype=float).reshape(3,2)

array([[ 2.,  4.],
       [ 6.,  8.],
       [10., 12.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linspace(3,9,6)

array([3. , 4.2, 5.4, 6.6, 7.8, 9. ])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=np.arange(1,10).reshape(3,3)

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.rand(3,3)

array([[0.44387652, 0.73308474, 0.52119422],
       [0.98074102, 0.6751802 , 0.60566523],
       [0.72194685, 0.3194661 , 0.12256244]])

In [ ]:
np.linspace(-10,10,10)  #at equal distance generates points

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
I=np.identity(3)

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [ ]:
a.ndim

2

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.itemsize

8

In [ ]:
a.shape

(3, 3)

In [ ]:
#Changing Data type
a

array([1, 2, 3])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
 a.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [ ]:
  a1=np.arange(12).reshape(3,4)


In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a2.max()

23

In [ ]:
a2.mean()

17.5

In [ ]:
a1.prod()

0

<h1> 0---> Column <br> 1---> Rows

In [ ]:
np.max(a1,axis=1)

array([ 3,  7, 11])

### **Dot Product**

In [ ]:
a3=np.arange(2,11).reshape(3,3)

In [ ]:
a3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
 a4=np.arange(12,21).reshape(3,3)

In [ ]:
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
np.dot(a3,a4)

array([[141, 150, 159],
       [276, 294, 312],
       [411, 438, 465]])

In [ ]:
 np.arange(1,5).reshape(2,2)

array([[1, 2],
       [3, 4]])

<h1> Slicing </h1>

In [ ]:
a=np.array([1n,2,3,4,5,6])

SyntaxError: invalid decimal literal (<ipython-input-12-370db23164a0>, line 1)

In [ ]:
a=np.arange(1,10)

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:5:2]

array([3, 5])

In [ ]:
a2

NameError: name 'a2' is not defined

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1

NameError: name 'a1' is not defined

In [ ]:
a3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
a3[0,:] #complete row 0 refers to row position and : refers to all columns

array([2, 3, 4])

In [ ]:
a3[:,2]  #Here : refers to all rows while 2 refers to thrid column

array([ 4,  7, 10])

In [ ]:
a3[:,1]

array([3, 6, 9])

In [ ]:
 a2=np.arange(0,12).reshape(3,4)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2 ,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
   a2[1,0::3]

array([4, 7])

In [ ]:
 a3=np.arange(27).reshape(3,3,3)

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [61]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### **Iterating**

In [63]:
  a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9


In [66]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [67]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [68]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# **Reshaping**

In [69]:
#transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [71]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [72]:
#Ravel: converts in 1D

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### **Stacking**

In [75]:
#Horizontal: same rows but increase in columns
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [78]:
a6=np.hstack((a4,a5))

In [79]:
a7=np.vstack((a4,a5))

In [81]:
a6

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

## **Splitting**

In [83]:
#Horizontal: Opposite of Stacking
np.hsplit(a6,4)


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [87]:
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [88]:
np.vsplit(a7,6)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]