<a href="https://colab.research.google.com/github/rehanmehdichandio/Numpy-Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###What is Numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [4]:
#np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
# 2D 3D numpy arrya
b = np.array([[1,2,3], [4,5,6]])
print(b)

print("This is 3D numpy array / Tensor")
c = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [1,1,1]]])
print(c)

[[1 2 3]
 [4 5 6]]
This is 3D numpy array / Tensor
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 1 1]]]


In [16]:
#dtype

np.array([1,2,3], dtype= float)

array([1., 2., 3.])

In [6]:
#np.arange

a = np.arange(1,11,2)

In [7]:
#with reshape  //important
a1 = np.arange(1,13).reshape(4,3)

In [9]:
#np.ones and np.zeros

np.ones((3,4),dtype= int)

a2 = np.zeros ((3,2), dtype=int)


In [27]:
#np.random

np.random.random((2,3))

array([[0.01735725, 0.67412898, 0.85153516],
       [0.85797541, 0.73707552, 0.40154693]])

In [31]:
#np.linspace
np.linspace(1,9,9, dtype=int).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
#np.identity
np.identity(3, dtype = int)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

###Array Attributes

In [11]:
#ndim

a.ndim
a1.ndim


2

In [14]:
#Shape
a2.shape

print(a2.shape)
a2

(3, 2)


array([[0, 0],
       [0, 0],
       [0, 0]])

In [16]:
#size --> number of elements
a2.size

6

In [17]:
#itemsize --> memory size
a2.itemsize

8

In [20]:
#dtype

a2.dtype

dtype('int64')

###Changing Data Type

In [22]:
#astype
a3 = np.arange(1,10).reshape(3,3)
a3.astype(np.int32)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

###Array Operations

In [32]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [27]:
#Scalar Operations

#arithmatic

a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [29]:
#relational

a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
#vector operations
#arithmatic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

###Array Functions

In [37]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100).astype(np.int32)
a1
a1

a1

array([[11, 77, 55],
       [91, 54, 94],
       [60, 65, 81]], dtype=int32)

In [45]:
#min/max/sum/prod
# print(np.max(a1))
# print(np.min(a1))
# print(np.sum(a1))
# print(np.prod(a1))


print(np.max(a1, axis=1))

[77 94 81]


In [50]:
#mean/median/std/var
print("The mean of a1 is ", np.mean(a1))
print("The median of a1 is ", np.median(a1))
print("The standard deviation of a1 is ", np.std(a1))
print("The variance of a1 is ", np.var(a1))

The mean of a1 is  65.33333333333333
The median of a1 is  65.0
The standard deviation of a1 is  23.753362335093154
The variance of a1 is  564.2222222222222


In [51]:
#trigonometric functions
np.sin(a1)



array([[-0.99999021,  0.99952016, -0.99975517],
       [ 0.10598751, -0.55878905, -0.24525199],
       [-0.30481062,  0.82682868, -0.62988799]])

In [52]:
#dot product

In [57]:
a = np.arange(1,7).reshape(2,3)
b= np.arange(8,14).reshape(3,2)

a

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
b

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [59]:
#dot product
np.dot(a,b)

array([[ 64,  70],
       [154, 169]])

In [61]:
#log / exponents

np.log(a1)
np.exp(a1)

array([[5.98741417e+04, 2.75851345e+33, 7.69478527e+23],
       [3.31740010e+39, 2.83075330e+23, 6.66317622e+40],
       [1.14200739e+26, 1.69488924e+28, 1.50609731e+35]])

In [65]:
#round / floor / ceil

np.round(np.random.random((2,2))*100)


array([[23., 43.],
       [64., 78.]])

In [66]:
#round / floor / ceil

np.floor(np.random.random((2,2))*100)

array([[14., 46.],
       [ 2., 97.]])

In [67]:
#round / floor / ceil

np.ceil(np.random.random((2,2))*100)

array([[26., 55.],
       [ 8., 51.]])

###Indexing and Slicing

In [68]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [69]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a1[-1]

np.int64(9)

In [71]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
a2[1,2]

np.int64(6)

In [75]:
a2[2,3]

np.int64(11)

In [76]:
a2[1,0]

np.int64(4)

In [77]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [81]:
a3[1,0,1]   #Here in 1,0,1 defines that 1 refers to the matrix,0 refers to the row and again 1 refers to the column

np.int64(5)

In [82]:
a3[1,0,0]

np.int64(4)

In [83]:
a3[0,0,0]

np.int64(0)

In [84]:
a3[1,1,0]

np.int64(6)

In [85]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a1[2:5]

array([2, 3, 4])

In [89]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
a2[0,:]

array([0, 1, 2, 3])

In [92]:
a2[:, 2]

array([ 2,  6, 10])

In [95]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [96]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [97]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])